// Registers the recompiled code sections with librecomp.

#include <cstdio>
#include <cstring>

#ifdef _WIN32
#   include <Windows.h>
#else
#   include <sys/mman.h>
#endif

#include "librecomp/overlays.hpp"

#include "conker.hpp"

extern "C" {
    // RecompiledFuncs/tlb_pages.c, generated by recomp/emit_tlb_pages.py.
    extern const uint32_t conker_game_segment_vram;
    extern const size_t conker_game_segment_size;
    extern const uint32_t conker_game_segment[];
    extern const uint32_t conker_game_segment_rom;
    extern const uint32_t conker_debugger_segment_vram;
    extern const size_t conker_debugger_segment_size;
    extern const uint32_t conker_debugger_segment[];
    extern const uint32_t conker_debugger_segment_rom;
    extern const uint32_t conker_code_rewrites[][2];
    extern const size_t conker_code_rewrite_count;
}

// Generated by N64Recomp: section_table, num_sections, overlay_sections_by_index.
#include "recomp_overlays.inl"

void conker::register_overlays() {
    const recomp::overlays::overlay_section_table_data_t sections{
        .code_sections = section_table,
        .num_code_sections = ARRLEN(section_table),
        .total_num_sections = num_sections,
    };
    const recomp::overlays::overlays_by_index_t overlays{
        .table = overlay_sections_by_index,
        .len = ARRLEN(overlay_sections_by_index),
    };
    recomp::overlays::register_overlays(sections, overlays);
}

// librecomp's init only registers the code in the first megabyte of ROM, and at
// the ROM header's KSEG0 entrypoint (0x80001000). Conker runs its code at
// TLB-mapped addresses instead: .init through a TLB alias of KSEG0 at
// 0x10001000, .game and .debugger demand-paged at 0x15000000 and 0x16000000.
// Register each section at the address its code and function pointers use.
void conker::register_tlb_mapped_code() {
    load_overlays(0x00001000, 0x10001000, 0x000280D0); // .init
    load_overlays(0x0002D4B0, 0x15000000, 0x001FA130); // .game
    load_overlays(0x00255880, 0x16000000, 0x00004D58); // .debugger
}

// On the N64, .game and .debugger are TLB-mapped pages, and some code reads data
// that lives in them: lookup tables inside the hand-written math code (e.g.
// 0x150AA318) and the debugger's rodata. The runtime reserves 4GB for game memory
// but only maps RDRAM, so make the matching part of the reservation readable and
// fill it with the original segment contents.
static bool map_segment(uint8_t* rdram, uint32_t vram, const uint32_t* words, size_t size) {
    uint8_t* host = rdram + ((int64_t)(int32_t)vram + 0x80000000LL);
    constexpr uintptr_t page = 0x10000;
    uint8_t* begin = (uint8_t*)((uintptr_t)host & ~(page - 1));
    uint8_t* end = (uint8_t*)(((uintptr_t)host + size + page - 1) & ~(page - 1));
#ifdef _WIN32
    DWORD old;
    bool ok = VirtualProtect(begin, end - begin, PAGE_READWRITE, &old) != 0;
#else
    bool ok = mprotect(begin, end - begin, PROT_READ | PROT_WRITE) == 0;
#endif
    if (!ok) {
        std::fprintf(stderr, "[overlays] could not map 0x%08X (+0x%zX)\n", vram, size);
        return false;
    }
    // The runtime keeps each 32-bit word in host order, as these arrays already are.
    std::memcpy(host, words, size);
    return true;
}

void conker::map_tlb_code_pages(uint8_t* rdram) {
    map_segment(rdram, conker_game_segment_vram, conker_game_segment, conker_game_segment_size);
    map_segment(rdram, conker_debugger_segment_vram, conker_debugger_segment, conker_debugger_segment_size);
}

// The ROM as the recompiled code sees it, for mods' RECOMP_HOOKs: the runtime
// rebuilds a hooked function from its instructions at the function's ROM address.
// .game is compressed in the real ROM, and the recompiler's layout puts .game and
// .debugger at the decomp's uncompressed ROM addresses, so write the original
// segments there (in the ROM's big-endian byte order), plus the words
// prepare_elf.py rewrote, so a hooked function matches its recompiled version.
// .init is uncompressed at its real ROM address already.
std::vector<uint8_t> conker::decompress_rom(std::span<const uint8_t> rom) {
    std::vector<uint8_t> out(rom.begin(), rom.end());
    auto put_word = [&out](uint32_t rom_addr, uint32_t word) {
        if (out.size() < rom_addr + 4) {
            out.resize(rom_addr + 4);
        }
        out[rom_addr + 0] = (uint8_t)(word >> 24);
        out[rom_addr + 1] = (uint8_t)(word >> 16);
        out[rom_addr + 2] = (uint8_t)(word >> 8);
        out[rom_addr + 3] = (uint8_t)(word >> 0);
    };
    auto put_segment = [&](uint32_t rom_addr, const uint32_t* words, size_t size) {
        for (size_t i = 0; i < size / 4; i++) {
            put_word(rom_addr + 4 * i, words[i]);
        }
    };
    put_segment(conker_game_segment_rom, conker_game_segment, conker_game_segment_size);
    put_segment(conker_debugger_segment_rom, conker_debugger_segment, conker_debugger_segment_size);
    for (size_t i = 0; i < conker_code_rewrite_count; i++) {
        put_word(conker_code_rewrites[i][0], conker_code_rewrites[i][1]);
    }
    return out;
}
