#!/usr/bin/env python3
"""
Emit the TLB-mapped code segments as C arrays for the host.

Conker's hand-written code reads lookup tables stored inside its own TLB-mapped
code pages (e.g. 0x150AA318), and the debugger reads its rodata at 0x1600xxxx.
The host copies these arrays to the matching addresses in the runtime's memory
at startup (host/src/overlays.cpp). Words are emitted as N64 32-bit values,
which is the runtime's in-memory layout on a little-endian host.

The ELF gives each section's address and size; the bytes come from the original
segment dumps, so the copy is exactly what the game had (not the prepared ELF,
whose code has recompiler-specific rewrites).

Usage: emit_tlb_pages.py <prepared.elf> <out.c> .game=game.us.bin .debugger=debugger.us.bin
"""
import struct
import sys

SEGMENTS = [(".game", "conker_game_segment"), (".debugger", "conker_debugger_segment")]


def main(elf_path, out_path, originals):
    data = open(elf_path, "rb").read()
    shoff, = struct.unpack_from(">I", data, 0x20)
    shentsize, shnum, shstrndx = struct.unpack_from(">HHH", data, 0x2E)
    shdrs = [struct.unpack_from(">10I", data, shoff + i * shentsize) for i in range(shnum)]
    strtab = shdrs[shstrndx][4]
    name = lambda sh: data[strtab + sh[0]:data.index(b"\0", strtab + sh[0])].decode()
    out = ["// Generated by recomp/emit_tlb_pages.py from the original code. Do not edit.",
           "#include <stdint.h>", "#include <stddef.h>", ""]
    for sec, sym in SEGMENTS:
        sh = next(sh for sh in shdrs if name(sh) == sec)
        vram, off, size = sh[3], sh[4], sh[5]
        blob = open(originals[sec], "rb").read()
        words = struct.unpack_from(f">{size // 4}I", blob, 0)
        out.append(f"const uint32_t {sym}_vram = 0x{vram:08X};")
        out.append(f"const size_t {sym}_size = 0x{size:X};")
        out.append(f"const uint32_t {sym}[] = {{")
        for k in range(0, len(words), 8):
            out.append("    " + ", ".join(f"0x{w:08X}" for w in words[k:k + 8]) + ",")
        out.append("};")
        out.append("")
    open(out_path, "w").write("\n".join(out))


if __name__ == "__main__":
    if len(sys.argv) != 5:
        sys.exit(__doc__)
    main(sys.argv[1], sys.argv[2], dict(a.split("=", 1) for a in sys.argv[3:]))
