#!/usr/bin/env python3
"""
Emit the TLB-mapped code segments as C arrays for the host.

Conker's hand-written code reads lookup tables stored inside its own TLB-mapped
code pages (e.g. 0x150AA318), and the debugger reads its rodata at 0x1600xxxx.
The host copies these arrays to the matching addresses in the runtime's memory
at startup (host/src/overlays.cpp). Words are emitted as N64 32-bit values,
which is the runtime's in-memory layout on a little-endian host.

The ELF gives each section's address and size; the bytes come from the original
segment dumps, so the copy is exactly what the game had (not the prepared ELF,
whose code has recompiler-specific rewrites).

The same arrays give mods the uncompressed code that RECOMP_HOOK needs (the
runtime recompiles a hooked function from its original instructions; .game is
compressed in the ROM). For that, each segment's ROM address in the recompiled
layout (N64Recomp's section rom_addr) is emitted too, along with the words
prepare_elf.py rewrote in all code sections (.init included), so a hooked
function is rebuilt from the same instructions as the rest of the game.

Usage: emit_tlb_pages.py <prepared.elf> <out.c> .init=init.us.bin .game=game.us.bin .debugger=debugger.us.bin
"""
import struct
import sys

SEGMENTS = [(".game", "conker_game_segment"), (".debugger", "conker_debugger_segment")]
CODE_SECTIONS = [".init", ".game", ".debugger"]


def main(elf_path, out_path, originals):
    data = open(elf_path, "rb").read()
    shoff, = struct.unpack_from(">I", data, 0x20)
    shentsize, shnum, shstrndx = struct.unpack_from(">HHH", data, 0x2E)
    shdrs = [struct.unpack_from(">10I", data, shoff + i * shentsize) for i in range(shnum)]
    strtab = shdrs[shstrndx][4]
    name = lambda sh: data[strtab + sh[0]:data.index(b"\0", strtab + sh[0])].decode()
    phoff, = struct.unpack_from(">I", data, 0x1C)
    phentsize, phnum = struct.unpack_from(">HH", data, 0x2A)
    phdrs = [struct.unpack_from(">8I", data, phoff + i * phentsize) for i in range(phnum)]

    def rom_addr(sh):
        # As N64Recomp computes it: the load segment's physical address plus the
        # section's offset into it.
        for p_type, p_offset, _, p_paddr, p_filesz, *_ in phdrs:
            if p_type == 1 and p_offset <= sh[4] < p_offset + p_filesz:
                return p_paddr + sh[4] - p_offset
        sys.exit(f"emit_tlb_pages: no load segment holds the section at file offset {sh[4]:#x}")

    out = ["// Generated by recomp/emit_tlb_pages.py from the original code. Do not edit.",
           "#include <stdint.h>", "#include <stddef.h>", ""]
    for sec, sym in SEGMENTS:
        sh = next(sh for sh in shdrs if name(sh) == sec)
        vram, off, size = sh[3], sh[4], sh[5]
        blob = open(originals[sec], "rb").read()
        words = struct.unpack_from(f">{size // 4}I", blob, 0)
        out.append(f"const uint32_t {sym}_vram = 0x{vram:08X};")
        out.append(f"const uint32_t {sym}_rom = 0x{rom_addr(sh):08X};")
        out.append(f"const size_t {sym}_size = 0x{size:X};")
        out.append(f"const uint32_t {sym}[] = {{")
        for k in range(0, len(words), 8):
            out.append("    " + ", ".join(f"0x{w:08X}" for w in words[k:k + 8]) + ",")
        out.append("};")
        out.append("")
    # Words the prepared ELF changed (prepare_elf.py's return rewrites), by ROM address.
    out.append("const uint32_t conker_code_rewrites[][2] = {")
    count = 0
    for sec in CODE_SECTIONS:
        sh = next(sh for sh in shdrs if name(sh) == sec)
        off, size = sh[4], sh[5]
        blob = open(originals[sec], "rb").read()
        for k in range(0, size, 4):
            if data[off + k:off + k + 4] != blob[k:k + 4]:
                word, = struct.unpack_from(">I", data, off + k)
                out.append(f"    {{ 0x{rom_addr(sh) + k:08X}, 0x{word:08X} }}, // {sec} 0x{sh[3] + k:08X}")
                count += 1
    out.append("};")
    out.append(f"const size_t conker_code_rewrite_count = {count};")
    out.append("")
    open(out_path, "w").write("\n".join(out))


if __name__ == "__main__":
    if len(sys.argv) != 6:
        sys.exit(__doc__)
    main(sys.argv[1], sys.argv[2], dict(a.split("=", 1) for a in sys.argv[3:]))
